// Wobble eligibility per biome-map color, sourced from
// `data/biome_flags.json` (generated by `scripts/generate.mjs biome-flags`
// from each biome XML's `noise_biome_edges` attribute, which sets the
// per-chunk +0xC4 byte that gates Noita's edge wobble).

import biomeFlagsData from '../data/biome_flags.json' with { type: 'json' };

const KNOWN_BIOME_COLORS = new Set();
const INELIGIBLE_BIOME_COLORS = new Set();
for (const b of biomeFlagsData.biomes) {
    const rgb = parseInt(b.color, 16) & 0xffffff;
    KNOWN_BIOME_COLORS.add(rgb);
    if (b.ineligible) INELIGIBLE_BIOME_COLORS.add(rgb);
}

// Returns the eligibility verdict for a biome-map RGB color:
//   'ineligible' → noise_biome_edges="0" — skip the wobble.
//   'eligible'   → noise_biome_edges absent or "1" — wobble normally.
//   'unknown'    → not in data/biome_flags.json (e.g. NG+ palette swaps);
//                  callers should fall back to a different heuristic.
export function colorWobbleVerdict(colorInt) {
    const rgb = colorInt & 0xffffff;
    if (!KNOWN_BIOME_COLORS.has(rgb)) return 'unknown';
    return INELIGIBLE_BIOME_COLORS.has(rgb) ? 'ineligible' : 'eligible';
}

export const BIOME_FLAGS = biomeFlagsData;
