// Per-biome edge-noise flags, sourced from `data/biome_flags.json`
// (generated by `scripts/generate.mjs biome-flags` — XML attributes
// passed through verbatim). Noita's edge-noise resolver
// `ChunkGrid_ResolveChunkAtPosition` @ 0x0087d9a0 reads three per-chunk
// bytes set from biome XML attributes; two are surfaced here:
//
//   noise_biome_edges  default 1 — gates the wobble entirely
//                      (0 ⇒ straight chunk edges).
//   fat_biome_edges    default 0 — non-zero short-circuits the resolver
//                      back to the original chunk. A handful of solid-
//                      wall / teleroom biomes explicitly declare it as
//                      0 (redundant with the default).
//
// The third attribute `big_noise_biome_edges` (+0xC5) would switch the
// resolver to its simplex-only branch when either side of an edge has
// it set to 0, but no biome in the known data.wak unpack declares it —
// so it's omitted from both the generator and this module. Defaults
// were confirmed against the noitrainer runtime dump at
// `data/dumps/biome_flags.ndjson.gz`.

import biomeFlagsData from '../data/biome_flags.json' with { type: 'json' };

const EDGE_NOISE_DEFAULTS = {
    noise_biome_edges: 1,
    fat_biome_edges: 0,
};

const KNOWN_BIOME_COLORS = new Set();
const BIOME_FLAGS_BY_COLOR = new Map();
for (const b of biomeFlagsData.biomes) {
    const rgb = parseInt(b.color, 16) & 0xffffff;
    KNOWN_BIOME_COLORS.add(rgb);
    BIOME_FLAGS_BY_COLOR.set(rgb, b);
}

// Look up a single edge-noise attribute for a biome-map RGB color. Returns
// the engine-default when the attribute isn't declared in the biome's XML,
// or `null` for unknown colors (e.g. NG+ palette swaps missing from the
// data.wak unpack) so callers can fall back without tripping a default.
export function biomeEdgeNoiseFlag(colorInt, attr) {
    const rgb = colorInt & 0xffffff;
    if (!KNOWN_BIOME_COLORS.has(rgb)) return null;
    const entry = BIOME_FLAGS_BY_COLOR.get(rgb);
    return entry[attr] ?? EDGE_NOISE_DEFAULTS[attr];
}

export const BIOME_FLAGS = biomeFlagsData;
