/* global process, Buffer */
// Packs the 16x16 icon folders into one sprite sheet each (data/<folder>.sheet.png)
// plus js/icon_sheet_index.js, which js/icon_sheets.js reads to place an icon.
// Rerun after adding or changing an icon in any of SHEET_FOLDERS;
// test/icon_sheets.test.mjs fails until you do.
//
// Cells are 18px with the icon at (1,1): the transparent gutter keeps a scaled
// icon from sampling its neighbour's edge at fractional device-pixel ratios.
// The sheet holds the icons' raw pixel values, ignoring any gAMA/iCCP chunk,
// like every other PNG this app reads (js/png_sanitizer.js).
//
// Run: node tools/build_icon_sheets.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import UPNG from 'upng-js';

export const SHEET_FOLDERS = ['perk_sprites', 'spell_sprites'];
const ICON = 16, CELL = 18;
const DATA = new URL('../data/', import.meta.url);

export function buildIconSheet(folder) {
	const dir = new URL(`${folder}/`, DATA);
	const names = readdirSync(dir).filter(f => f.endsWith('.png')).map(f => f.slice(0, -4)).sort();
	const cols = Math.ceil(Math.sqrt(names.length));
	const rows = Math.ceil(names.length / cols);
	const width = cols * CELL, height = rows * CELL;
	const sheet = new Uint8Array(width * height * 4);
	names.forEach((name, i) => {
		const img = UPNG.decode(readFileSync(new URL(`${name}.png`, dir)));
		if (img.width !== ICON || img.height !== ICON) {
			throw new Error(`${folder}/${name}.png is ${img.width}x${img.height}, not ${ICON}x${ICON}`);
		}
		const rgba = new Uint8Array(UPNG.toRGBA8(img)[0]);
		const x0 = (i % cols) * CELL + 1, y0 = Math.floor(i / cols) * CELL + 1;
		for (let y = 0; y < ICON; y++) {
			sheet.set(rgba.subarray(y * ICON * 4, (y + 1) * ICON * 4), ((y0 + y) * width + x0) * 4);
		}
	});
	return { names, cols, width, height, pixels: sheet };
}

export function iconSheetIndexSource(sheets) {
	const entries = sheets.map(({ folder, names, cols, width, height }) =>
		`\t${folder}: { url: 'data/${folder}.sheet.png', cell: ${CELL}, icon: ${ICON}, cols: ${cols}, width: ${width}, height: ${height},\n` +
		`\t\tnames: ${JSON.stringify(names)} },`);
	return `// Generated by tools/build_icon_sheets.mjs -- do not edit.\nexport const ICON_SHEETS = {\n${entries.join('\n')}\n};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
	const sheets = SHEET_FOLDERS.map(folder => ({ folder, ...buildIconSheet(folder) }));
	for (const s of sheets) {
		const png = UPNG.encode([s.pixels.buffer], s.width, s.height, 0);
		writeFileSync(new URL(`${s.folder}.sheet.png`, DATA), Buffer.from(png));
		console.log(`data/${s.folder}.sheet.png: ${s.names.length} icons, ${s.width}x${s.height}, ${png.byteLength} bytes`);
	}
	writeFileSync(new URL('../js/icon_sheet_index.js', import.meta.url), iconSheetIndexSource(sheets));
}
